services:
  api-gateway:
    image: ruthwikkakumani/api-gateway:latest
    container_name: api-gateway
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - ENV=${ENV}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - URL_SERVICE_URL=${URL_SERVICE_URL}
    depends_on:
      - auth-service
      - url-service
    restart: unless-stopped
  
  auth-service:
    image: ruthwikkakumani/auth-service:latest
    env_file:
      - .env
    container_name: auth-service
    environment:
      - ENV=${ENV}
      - PORT=${AUTH_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - DB_CONN=${DB_CONN_AUTH}
    restart: unless-stopped

  url-service:
    image: ruthwikkakumani/url-service:latest
    env_file:
      - .env
    container_name: url-service
    environment:
      - ENV=${ENV}
      - PORT=${URL_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - BASE_URL=${BASE_URL}
      - DB_CONN=${DB_CONN_URL}
    restart: unless-stopped
