services:
  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - ENV=${ENV}
      - PORT=${AUTH_PORT}
      - JWT_SECRET=${JWT_SECRET}
      # - DB_CONN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-auth:5432/${AUTH_DB_NAME}?sslmode=disable
      - DB_CONN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@url-shortener-db.cy7wykyyqtnk.us-east-1.rds.amazonaws.com:5432/${AUTH_DB_NAME}?sslmode=disable
    restart: unless-stopped

  url-service:
    build:
      context: .
      dockerfile: services/url-service/Dockerfile
    container_name: url-service
    ports:
      - "8082:8082"
    environment:
      - ENV=${ENV}
      - PORT=${URL_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - BASE_URL=${BASE_URL}
      # - DB_CONN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-url:5432/${URL_DB_NAME}?sslmode=disable
      - DB_CONN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@url-shortener-db.cy7wykyyqtnk.us-east-1.rds.amazonaws.com:5432/${URL_DB_NAME}?sslmode=disable
    restart: unless-stopped